kevincobain2000/gobrew

- build.sh
HI @kevincobain2000, thank you for a quick merge of my previous PR. 
Unfortunately, it was too quick and I had a small problem in it. The binary name has a mismatch in the build file and the file to download it. This PR fixes it.
Ref: https://github.com/kevincobain2000/gobrew/pull/21
> Fix binary name for mac m1

- cmd/gobrew/main.go
Fixes the problem below
$gobrew ls-remote
.......
1.17	1.17.0  1.17.1  1.17.2  1.17.3  1.17.4  1.17.5  1.17.6  1.17.7  1.17.8  1.17beta1  1.17rc1  1.17rc2
$gobrew install 1.17.0
[Info] Downloading version: 1.17.0
[Success] Untar to /Users/xxxxx/.gobrew/versions/1.17.0
[Info]: Untar failed: exit status 1
[Error]: Please check if version exists from url: https://golang.org/dl/go1.17.0.darwin-amd64.tar.gz
> fixes: Some versions cannot be downloaded and installed, such as 1.17.0, etc

- .github/workflows/release.yml
- .gitignore
- .goreleaser.yaml
- git.io.sh
Repository contains a lot binary files.
We should use Release pages for storing release binary files.
Example usage:
[v1.6.2](https://github.com/juev/gobrew/releases/tag/v1.6.2)
We only should create new tag with version, after that automatically start new build with creating binary files, publishing these files to release page and update it with changelog.
Currently we create binary for linux, darwin, windows and freebsd.
Script for installation was updated for using latest release page.
One note: for remove binary files from repository you should rewrite history.
Close #34
> feat: use goreleaser for release

- cmd/gobrew/main.go
From [goreleaser/build](https://goreleaser.com/customization/build/):
By default we have several variables by builds:
- version
- commit
- date
- builtBy
We can use it in main program.
In this time we use only version variable.
For local build without goreleaser version setting to `dev`.
Example build:
https://github.com/juev/gobrew/releases/tag/v1.6.5
Local build with go build:
```bash
~/Pr/Gi/gobrew on  version [?]
15:07:23  ❯ ./gobrew
gobrew dev
```
> feat: use version from goreleaser

- gobrew_test.go
```
--- FAIL: TestJudgeVersion (1.03s)
--- FAIL: TestJudgeVersion/dev-latest (0.12s)
gobrew_test.go:54: assertion failed: 1.19rc2 (test.wantVersion string) != 1.19 (version string)
```
UT should pass: https://github.com/kevincobain2000/gobrew/pull/41
> 1.19 got released?

- README.md
- utils/utils.go
Fixes https://github.com/kevincobain2000/gobrew/issues/52
Shows output as
```
[Info] Downloading to: /Users/pulkit.kathuria/.gobrew/downloads
[Info]: Downloading version failed: https://golang.org/dl/go1.14.darwin-arm64.tar.gz 404 not found
[Error]: Please check connectivity to url: https://golang.org/dl/go1.14.1.darwin-amd64.tar.gz
exit status 1
```
> error when unknown package is downloaded

- gobrew.go
■ Before
```
1.17	1.17.0  1.17.1  1.17.2  1.17.3  1.17.4
1.17.5  1.17.6  1.17.7  1.17.8  1.17.9  1.17.10
1.17.11  1.17.12  1.17.13  1.17beta1  1.17rc1  1.17rc2
1.18	1.18.0  1.18.1  1.18.2  1.18.3  1.18.4
1.18.5  1.18.6  1.18.7  1.18beta1  1.18beta2  1.18rc1
1.19	1.19.0  1.19.1  1.19.2  1.19beta1  1.19rc1  1.19rc2
```
■ After
```
1.17	1.17.0  1.17.1  1.17.2  1.17.3  1.17.4
1.17.5  1.17.6  1.17.7  1.17.8  1.17.9  1.17.10
1.17.11  1.17.12  1.17.13
1.17beta1  1.17rc1  1.17rc2
1.18	1.18.0  1.18.1  1.18.2  1.18.3  1.18.4
1.18.5  1.18.6  1.18.7
1.18beta1  1.18beta2  1.18rc1
1.19	1.19.0  1.19.1  1.19.2
1.19beta1  1.19rc1  1.19rc2
```
> put rc beta in new line

- git.io.sh
Adding `"...\n"` prints the newline character literally, resulting in `Installing gobrew...\n`, rather than an additional new line.
Adding an empty `echo ""` prints a blank line, which is what I think was intended :)
Either way, thanks for building this!
> fixing newline echo statement

- gobrew.go
This PR fixes the version evaluation and the archive download to make it work on Windows.
It changes CurrentVersion function to use the operating system path separator during the file name cleanup.
It also changes the downloadAndExtract function to download the zip file when the program is running on Windows.
> Add windows support for version check and download

- README.md
- gobrew.go
- gobrew_test.go
This PR fixes the following items:
- `self-update` command when running on Windows.
It also contains some updates:
- Documentation about the symbolic links support on Windows.
- The expected version on `TestJudgeVersion` test.
> Add Windows support for self-update command

- cmd/gobrew/main.go
- gobrew.go
- gobrew_test.go
This make possible to use the tool on Windows without the need of create the HOME environment variable using portable go code.
Method os.UserHomeDir returns the current user's home directory.
* On Unix, including macOS, it returns the $HOME environment variable.
* On Windows, it returns %USERPROFILE%.
* On Plan 9, it returns the $home environment variable.
> Use portable code to find user home directory

- git.io.sh
This PR allow the install script to be runned on Windows using Git bash as it happens on gobrew github action.
After merging this it probably will be possible to enable the current actions to run on windows-latest too.
> Fix install script to work on Windows Git bash

- gobrew.go
- gobrew_test.go
On Windows the executable can not be removed while it is running, but we can rename it and then finish the upgrade.
Also added a new version of the constructor named `NewGoBrewDirectory`.
With this new constructor all tests related to version management and upgrade can run in isolated directories.
> Fix upgrade on windows and tests

- gobrew.go
Sometimes dir exists, which ends up showing that the version is installed.
However version checker checks for real binary instead of the existance of the dir.
Removing extra condition to fix prune and rm issues.
> Sometimes dir exists, which ends up showing that the version that doesn't exist

- .github/workflows/build.yml
- README.md
- cmd/gobrew/main.go
- gobrew.go
Not exactly fixing #99 but a step in this direction
Usage
```
gobrew use mod // reads version from go.mod file and use the latest version of that
```
> gobrew use mod

- cmd/gobrew/main.go
Fixes #113 
OK should have no impact
```
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/gobrew ‹feature/semantic-comply›
╰─$ go run cmd/gobrew/main.go install 1.21rc3
==> [Info] Downloading version: 1.21rc3
==> [Info] Downloading from: https://go.dev/dl/go1.21rc3.darwin-arm64.tar.gz
==> [Info] Downloading to: /Users/pulkit.kathuria/.gobrew/downloads
Downloading   0% |    
```
OK - should fail
```                                                                                                                                                                                                                     | (80 kB/62 MB, 288 kB/s) [0s:3m41s]^Csignal: interrupt
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/gobrew ‹feature/semantic-comply›
╰─$ go run cmd/gobrew/main.go install 1.21 …
```
> Fixes #113 where version 1.21.0 was falling back to 1.21

- .github/workflows/build.yml
- .github/workflows/coveritup.yml
- .github/workflows/test.yml
- README.md
> CI Github Actions

- gobrew.go
Before
```
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git
╰─$ gobrew prune
==> [Info] Current version: 1.21.1
==> [Info] Uninstalling version: 1.17
==> [Success] Version: 1.17 uninstalled
==> [Info] Uninstalled version: 1.17 <--------------- getting rid of this extra msg
==> [Info] Uninstalling version: 1.18
==> [Success] Version: 1.18 uninstalled
==> [Info] Uninstalled version: 1.18
==> [Info] Uninstalling version: 1.18.10
==> [Success] Version: 1.18.10 uninstalled
```
After
```
╰─$ go run cmd/gobrew/main.go prune
==> [Info] Current version: 1.21.1
==> [Info] Uninstalling version: 1.17
==> [Success] Version: 1.17 uninstalled
==> [Info] Uninstalling version: 1.18
==> [Success] Version: 1.18 uninstalled
```
> remove redundant msg

- gobrew.go
* check versionsSemantic/judgedVersions before processing
* if we get a 404 code from github when using a token, make a repeat request without a token
Closed: #139
> fix: processing invalid GITHUB_TOKEN

- gobrew.go
```
╰─$ go run cmd/gobrew/main.go use mod                                                                                                                                                                      
==> [Info] Fetching remote versions
==> [Info] Downloading version: mod
==> [Info] Downloading from: https://go.dev/dl/gomod.darwin-arm64.tar.gz
==> [Info] Downloading to: /Users/pulkit.kathuria/.gobrew/downloads
==> [Info] Downloading version failed: https://go.dev/dl/gomod.darwin-arm64.tar.gz returned status code 404
==> [Error]: Please check connectivity to url: https://go.dev/dl/gomod.darwin-arm64.tar.gz
↑ Fixes
```
> unable to obtain mod version

- cmd/gobrew/main.go
- gobrew.go
Fixes https://github.com/kevincobain2000/gobrew/issues/156
Outputs
```
╰─$ go run cmd/gobrew/main.go use 1.17.1
==> [Info] Downloading version: 1.17.1
==> [Info] Downloading from: https://go.dev/dl/go1.17.1.darwin-arm64.tar.gz
==> [Info] Downloading to: /Users/pulkit.kathuria/.gobrew/downloads
Downloading   0% |                                                                                                                                                                    | (128 kB/123 MB, 458 kB/s) [0s:4m35s]^Csignal: interrupt
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/gobrew ‹feature/version-1.21.0›
╰─$ go run cmd/gobrew/main.go use 1.17 …
```
> 1.21 -> 1.21.0

- .github/workflows/build.yml
- .github/workflows/coveritup.yml
- .github/workflows/test.yml
- cmd/gobrew/main.go
- cmd/gobrew/main_unix.go
- cmd/gobrew/main_windows.go
- gobrew.go
- gobrew_test.go
@kevincobain2000 
Conducted a small refactoring in the code base:
- do not use a global variable.  Now parallel running of tests will not lead to data races
- disabled the race check in regular tests, since we do not explicitly use goroutines.  The speed of passing tests should increase.  Alternatively, you can also disable it in coverit
- return None by default instead of an empty string
- in the listing of versions we immediately return versions without the go prefix
- in the main package I also divided it by operating system
- something else small
And by the way, the question is, why did you call the latest version v1.10.0?  And not 1.9.10?  There were no significant changes there either.
And I was faced with the fact that when changing the settings of coveritup.yml, the project build …
> Refactoring 08122023

- cmd/gobrew/main.go
- gobrew.go
- gobrew_test.go
- helpers.go
- helpers_test.go
- private functions to helpers
- public functions to gobrew
- use os variables only on main function
- setup gobrew with one function
- setup http client with timeouts
> Refactoring 09122023

- cmd/gobrew/main.go
- helpers.go
`gobrew ls-remote` didn't pick http proxy
> hotfix: work behind proxy

- gobrew.go
- gobrew_unix.go
- gobrew_windows.go
- helpers.go
1. Symlink on Windows 10 Powershell required privilege, so we need to use `cmd` to create a symlink with `mklink`. See issue https://github.com/kevincobain2000/gobrew/issues/174
2. `filepath.EvalSymlinks` doesn't work correctly on Windows. A fix is currently being proposed: https://github.com/golang/go/issues/63703
> Fix: Win10 symlink require privilege

- git.io.sh
Fixes #176 
```
╰─$ cat git.io.sh| sh -s -- v1.10.4
Installing gobrew from: https://github.com/kevincobain2000/gobrew/releases/download/v1.10.4/gobrew-darwin-arm64
######################################################################## 100.0%
Installed successfully to: /Users/pulkit.kathuria/.gobrew/bin/gobrew
============================
╰─$ gobrew version
[INFO] gobrew version is 1.10.4
```
Normally
```
╰─$ cat git.io.sh| sh
Installing gobrew from: https://github.com/kevincobain2000/gobrew/releases/latest/download/gobrew-darwin-arm64
######################################################################## 100.0%
╰─$ gobrew version
[INFO] gobrew version is 1.10.6
```
> installer script

- helpers.go
Fixes #179 
Semantic ordering is
```
[]string{
"1.22rc1",
"1.22rc2",
"1.22.0",
}
```
I wonder if it ever worked actually. It had been there since the beginning.
> pick the latest in order for `dev-latest`

- .github/workflows/golangci-lint.yml
- .golangci.yaml
- cmd/gobrew/main.go
- cmd/gobrew/main_windows.go
- go.mod
- gobrew.go
- gobrew_test.go
- helpers.go
- helpers_test.go
Using golangci-link makes it easier to check the code and avoid a lot of problems.
This is only a draft of changes so far.
First, after changing the golang version to 1.22 in the go.mod file, many utilities stopped working. According to issue, we corrected the version, specifying it more precisely. After that, everything worked as it should.
Performed adding a new pipe and configuration for golangci-lint to standardize checks.
At the current moment, we have a number of problems that I plan to fix in the current PR.
Please do not merge this changes until they are ready to go.
> Add golangci-lint

- cmd/gobrew/main_windows.go
After refactoring and allocating separate files to store messages for different systems, an error was made. Both the unix and windows files contained the same message.
This PR corrects this error.
> fix: help message for windows

- .github/workflows/coveritup.yml
- README.md
- gobrew_test.go
Woah, we have a lot of allocs. Thanks to your new mock tests we can now measure them.
> (feat) added benchmarks for a simple Go installation

- .github/workflows/release.yml
- .goreleaser.yaml
`goreleaser` has already been updated, as well as github action for it. I checked the configuration, everything is fine, except for the version. I also did the addition.
> feat: update goreleaser

- helpers.go
Fixed: #199
Since we add a local cache for 20 minutes to store information about golang tags, we can safely access the github api for information about tags. At the same time, we will not receive errors like too many requests.
Currently, the storage time in the cache is strictly specified in the program code and is 20 minutes. It is probably worth considering the ability to change this parameter in the future. If you consider it necessary, you can implement this in the current PR.
Also, adding a file with a local cache allows you to independently prepare this file in a number of environments and put it in the gobrew working directory. This will avoid additional requests to Github for tags. This is for question #197
I tested this solution locally.
> feat: use local cache for storing tag information

- git.io.sh
> fix: fail script process on errors

- git.io.sh
```
╰─$ cat git.io.sh| sh
🥳 Installing gobrew from: https://github.com/kevincobain2000/gobrew/releases/latest/download/gobrew-darwin-arm64
######################################################################## 100.0%
🔧 Installed successfully to: /Users/pulkit.kathuria/.gobrew/bin/gobrew
🚀 gobrew help
gobrew 1.10.11
Usage:
gobrew use <version>           Install and set <version>
gobrew ls                      Alias for list
gobrew ls-remote               List remote versions (including rc|beta versions)
gobrew install <version>       Only install <version> (binary from official or GOBREW_REGISTRY env)
gobrew uninstall <version>     Uninstall <version>
gobrew list                    List installed versions
gobrew self-update             Self update this tool
gobrew prune …
```
> hello: or not
