- .github/workflows/build.yml
- .github/workflows/reviewdog.yml
- .reviewdog.yml
- git.io.sh
- go.mod
> fixes: #4. POSIX compatible

- cmd/gobrew/main.go
- git.io.sh
- go.mod
- go.sum
- gobrew.go
> added colors and group remote version

- .github/workflows/build.yml
- README.md
Rc versions compatibility https://github.com/actions/setup-go/issues/135
> Use gobrew in actions

- build.sh
- git.io.sh
This PR adds a specific build for M1 machines.
> Add build for M1 mac

- README.md
- cmd/gobrew/main.go
- gobrew.go
> feat: registryPath from env GOBREW_REGISTRY

- gobrew.go
- fix upgrade functions when we check version
- fix panic when we have rate limits
- extend rate limits for github actions
> Rate limits

- .github/workflows/sync-release-tags.yml
- gobrew.go
Rate limit issue: https://github.com/kevincobain2000/gobrew/issues/45
Solution for the: https://github.com/kevincobain2000/gobrew/issues/45#issuecomment-1210126038
> rate limit fix by not using api.github

- .goreleaser.yaml
- git.io.sh
- gobrew_test.go
This PR will add new binary for raspberry
Closes #57
> Installation on raspberry

- gobrew_test.go
> all stable

- README.md
- cmd/gobrew/main.go
> handy advice - GOROOT

- gobrew.go
[#issue](https://github.com/kevincobain2000/gobrew/issues/63)
> https://github.com/kevincobain2000/gobrew/issues/63

- README.md
- cmd/gobrew/main.go
- gobrew.go
Fixes #65 
Fixes #68 (auto close 😄 )
> `gobrew version` and `gobrew prune`

- README.md
- gobrew.go
- gobrew_test.go
> Fixes #72 strange output

- gobrew.go
> fix: remove binary file before upgrade

- git.io.sh
- gobrew.go
> [Testing 中] Fixes #77 allow GOBREW_ROOT

- README.md
https://github.com/kevincobain2000/gobrew/issues/77#issuecomment-1376822107
> usage of GOBREW_ROOT

- .github/workflows/test.yml
- README.md
- gobrew.go
> windows support in full

- go.mod
- go.sum
- utils/utils.go
> fixes #102  light background

- completions/bash/gobrew-completion
I'm addicted to bash completion then i didnt read that 'self-update' command does exist
hope this small contribution helps
> adding "self-update" in gobrew-completion

- .github/workflows/release.yml
- .goreleaser.yaml
> fix: goreleaser config for gobrew version

- gobrew.go
> fix: check version before changing

- gobrew.go
- check statusCode from response
- add github token to request when available
> feat: check statusCode from response

- gobrew.go
fix #128 
I think this is one of the best solutions
> feat: do not print blacklisted versions

- .github/workflows/coveritup.yml
- README.md
> (ci) coveritup add time taken by unit tests

- .github/workflows/coveritup.yml
https://github.com/kevincobain2000/action-camo-purge
> purge badges

- gobrew.go
> fix: process errors on doRequest with exit

- gobrew.go
> only support go.mod major versions

- git.io.sh
Better to show a progress bar instead of silent
> Update git.io.sh - show progress bar

- .github/workflows/build.yml
- .github/workflows/coveritup.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- go.mod
Mod issue on 1.21 was fixed #157 #156
> CI should pass now

- .github/workflows/build.yml
- .github/workflows/coveritup.yml
- .github/workflows/test.yml
> And I was faced with the fact that when changing the settings of coveritup.yml, the project build did not start. That is, by changing the assembly process, I could not launch it without making changes to the project itself. Not very comfortable.
Fixes this
> should see yml and not yaml

- .github/workflows/golangci-lint.yml
- .github/workflows/release.yml
- .github/workflows/sync-release-tags.yml
- golangci/golangci-lint-action v4 -> v6
- goreleaser/goreleaser-action v4 -> v5
- peaceiris/actions-gh-pages v3 -> v4
> feat: update github actions

- gobrew.go
- helpers.go
- helpers_test.go
> fix: do not install not exist version

- git.io.sh
Fixes https://github.com/kevincobain2000/gobrew/issues/207
> Fix: Handle unset GOBREW_ROOT variable safely
